language: c

env:
 global:
  - EnableNuGetPackageRestore=true 

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
  - wget -O ./nuget.exe  http://nuget.org/nuget.exe
  - mono nuget.exe restore FileBlob.sln

script:
  - xbuild /property:Configuration=Release FileBlob.sln
 
  
